## Linear Algebra

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### Matrix Operation

In [21]:
A=np.array([[2,-1], 
            [0,3]])
B=np.array([[1,2],
            [-3,4]])
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[ 2 -1]
 [ 0  3]]
Matrix B:
[[ 1  2]
 [-3  4]]


##### 1. A+B

In [3]:
print(A+B)

[[ 3  1]
 [-3  7]]


##### 2. AB

In [21]:
A=np.array([[2,-1], 
            [0,3]])
B=np.array([[1,2],
            [-3,4]])
print(A @ B)

[[ 5  0]
 [-9 12]]


##### 3. 3A-2B

In [5]:
print(3*A-2*B)

[[ 4 -7]
 [ 6  1]]


### Determinant and Inverse

In [19]:
import numpy.linalg as LA
# For Determinant
A=np.array([[2,-1], 
            [0,3]])
Det=LA.det(A)
print("Determinant=",Det)
# For Inverse (As A is non-singular matrix)
if(Det==0):
    print("The matrix is not invertible.")
else:
 inverse=np.linalg.inv(A)
 print("Inverse:")
 print(inverse)

Determinant= 6.0
Inverse:
[[0.5        0.16666667]
 [0.         0.33333333]]


### Eigen value and Eigen vectors 

In [26]:
# Define the matrix
C=np.array([[4,1],
            [-2,1]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Matrix C:")
print(C)
print("\nEigenvalues:")
print(eigenvalues[0])
print(eigenvalues[1])
print("\nCorresponding Eigenvectors:")
print(eigenvectors[:,[0]])
print(eigenvectors[:,[1]])

Matrix C:
[[ 4  1]
 [-2  1]]

Eigenvalues:
3.0
2.0

Corresponding Eigenvectors:
[[ 0.70710678]
 [-0.70710678]]
[[-0.4472136 ]
 [ 0.89442719]]


### Price of Cars According to the Features

##### Dataset of cars with features:
##### x1= Number of cylinders
##### x2= Engine size in litres
##### x3= Horsepower
##### Car1: x1=4, x2=1.5, x3=100 and price:20
##### Car2: x1=6, x2=2.0, x3=150 and price:30
##### To find the price of Car3: x1=8, x2=3.0 ,x3=200 and price=?

In [25]:
F = np.array([[4,1.5,100],
              [6,2.0,150]])
Pr= np.array([[20],[30]])
inverse = np.linalg.pinv(F.T @ F)
B = inverse @ F.T @ Pr
X = np.array([[8,3.0,200]])
price = np.linalg.det(X @ B)
print("The price of the car3 is:",price)

The price of the car3 is: 40.00000000000069
